### PR TITLE
WIP fix(IDN): uriencode root value

### PR DESCRIPTION
**Pull request by curbengh**
The current approach does not encode the root value, this PR fixes that.
Similar to https://github.com/hexojs/hexo-generator-sitemap/pull/66

### CODE REVIEW

**Comment by curbengh** [comment]
`post.permalink` is empty throughout the unit test, not sure how to fix that.

This PR works in a test blog.

**Comment by curbengh** [comment]
Pending https://github.com/hexojs/hexo-util/pull/77

**Comment by tomap** [comment]
hexojs/hexo-util#77 merged

**Comment by curbengh** [comment]
Superseded by https://github.com/hexojs/hexo-generator-feed/pull/93

**Pull request closed without merging**
