### PR TITLE
chore: drop Node 10

### PR DESCRIPTION
**Pull request by curbengh**
BREAKING CHANGE
Camaro@6 requires Node 12+ (#145)

### CODE REVIEW

**Comment by tomap** [comment]
I'm sorry but I don't agree. Camaro is a dependency that is here only for testing. 
The fastest xml parser!
Does that justify dropping nodejs 10 ? which still has until April 2021 before EOL ?

Here are a few alternative: 
* https://github.com/NaturalIntelligence/fast-xml-parser#readme
* https://github.com/Leonidas-from-XIV/node-xml2js

**Comment by curbengh** [comment]
> Camaro is a dependency that is here only for testing.

It's a good point, I forgot that it's a devDependency here. Perhaps lock camaro to v5 (which still support Node 10)?

**Comment by SukkaW** [comment]
> Perhaps lock camaro to v5 (which still support Node 10) for now?

@tomap @curbengh It still depends on whether we will bump minimum required Node.js version for Hexo from 10 to 12.

**Comment by curbengh** [comment]
Even if it's bumped to 12 in Hexo, there's no compelling reason to do the same here, this plugin will not benefit from camaro@6.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-generator-feed/pull/151#issuecomment-671007850

**Pull request closed without merging**
