### PR TITLE
Make self feed url absolute

### PR DESCRIPTION
**Pull request by okelet**
According to https://validator.w3.org/feed/docs/warning/RelativeSelf.html

### CODE REVIEW

**Comment by tomap** [comment]
Indeed, I saw the same warning when trying to validate the feed

**Comment by puremana** [comment]
Is there a reason this hasn't been merged? I'm getting the same warning. I understand it's only a warning and has no impact, but if it can be fixed to prevent further confusion I think that would be a good idea.

**Comment by darekkay** [comment]
This PR has been open for 4 years now. I'd be happy to contribute (and e.g. resolve the merge conflicts), but I fear the work will be for nothing 🙁

**Comment by SukkaW** [comment]
@darekkay It will be appreciated if you going to address the PR again.

Also, the code here might help: https://github.com/hexojs/hexo-util/blob/master/lib/full_url_for.js

**Comment by darekkay** [comment]
Follow-up PR: https://github.com/hexojs/hexo-generator-feed/pull/143

**Comment by stevenjoezhang** [comment]
Thanks for your contribution!

**Pull request closed without merging**
