### PR TITLE
feat: support output in both atom and rss2

### LINKED ISSUE #59: Support rss2 and atom at the same time.
Well , i want my website provides the two types at the same time, can anyone do me a favour?

### PR DESCRIPTION
**Pull request by curbengh**
Fix #59 

How to test:
``` diff
package.json
-  "hexo-generator-feed": "^2.0.0"
+  "hexo-generator-feed": "curbengh/hexo-generator-feed#atom-rss2"
```

``` sh
$ rm -rf node_modules/ && npm i
```

``` yml
_config.yml
feed:
  type:
    - 'atom'
    - 'rss2'
```

``` sh
$ hexo clean && hexo g
```

cc @mythsman

### CODE REVIEW

**Comment by curbengh** [comment]
WIP, missing doc and unit test.

**Comment by curbengh** [comment]
Note that `generator.js` still output one file only, which is why it's called twice in `index.js`. This limitation also applies to the unit test, hence it doesn't check both atom and rss2 are generated; at least the test can check the order is correct.

The limitation doesn't apply to `autodiscovery`, so there is a unit test to check both values exist.

---

Although the code may be simpler if use `type: "both"` config, I prefer to explicitly use `type: ['atom, 'rss2']` for config readability.

**Comment by curbengh** [comment]
Ready for review.

**Comment by curbengh** [comment]
Rebased. Ready for review.

**Comment by tomap** [comment]
Maybe add in the doc an example of yaml with both output & both path so people don't struggle to type it

**Comment by curbengh** [comment]
> Maybe add in the doc an example of yaml with both output & both path 

+1. Added.

**Pull request merged**
