### PR TITLE
Add image enclosure with post.image metadata

### PR DESCRIPTION
**Pull request by oncletom**
When a `post` has an `image` front matter, it gets displayed as:

- `<enclosure type=image url="http://bloguri/{{ post.image }}" />` for RSS2 output
- `<content type=image src="http://bloguri/{{ post.image }}" />` for Atom output

### CODE REVIEW

**Comment by oncletom** [comment]
@YoshinoriN it's not a default value indeed.

I have built this assumption because the built-in [`open_graph()`](https://hexo.io/docs/helpers#open-graph) helper uses it. If the people who read the doc would use another official plugin, I'd assume I would use the same front matter name to display the same information.

[`jekyll-seo-tag`](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md) — it's not related to hexo but it makes the content more portable.

On the other hand, I can see there is a `photos` field in the Post model, but I have not yet seen a documentation about it either. 

What do you think? I can create a PR in hexo to make the `image` field explicit, and possibly use as a call for clarification about the `photos` field as well.

**Comment by YoshinoriN** [comment]
@oncletom 

> because the built-in open_graph() helper uses it. 

Oh, I didn't notice it. I think it's enough reason for merge this PR.

**Comment by oncletom** [comment]
Excellent. Let me know if you think of something else before merging this PR.

**Comment by YoshinoriN** [comment]
@oncletom 
I will going to test this PR on my local machine. Would you please wait a little ? Thanks.

**Comment by oncletom** [comment]
No problem :)

It's running on this website of mine for example ([source](https://github.com/oncletom/photography), [feed](https://oncletom.io/photography/atom.xml)).

**Comment by YoshinoriN** [comment]
Thanks. Done !

**Comment by oncletom** [comment]
Thank you 🙂

**Comment by oncletom** [comment]
Do you think you (or someone else) could tag a new (minor) release and publish it on npm?

**Comment by YoshinoriN** [comment]
No. I think it's better. But, I have not permission of publish to npm.
@NoahDragon & @JLHwung How do you think ?

**Comment by oncletom** [comment]
A good thing would be to deploy automatically on npm on a new Git tag.
TravisCI got you covered: https://docs.travis-ci.com/user/deployment/npm/

**Pull request merged**
